#version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: salespoint
    environment:
      POSTGRES_USER: lesson
      POSTGRES_PASSWORD: lesson
      POSTGRES_DB: salespoint
    ports:
      - "5440:5432"
    volumes:
      - ./salespoint-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin  #чтобы сохранялись настройки

    # Добавляем Swagger UI
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: salespoint-swagger-ui
    ports:
      - "8085:8080"
    environment:
      # Указываем URL вашего OpenAPI-документа (JSON/YAML)
      # Если API запущено локально (не в Docker) — используйте host.docker.internal
      SWAGGER_JSON: http://host.docker.internal:9050/v3/api-docs
      # это путь к апи сервиса
      # ИЛИ если API в этом же compose-файле — укажите имя сервиса:
      # SWAGGER_JSON: http://ваш_сервис_апи:порт/v3/api-docs
    depends_on:
      - postgres  # Зависит от Postgres (если API зависит от БД)
volumes:
  pgadmin_data: #в конце — обязательны для определения pgadmin_data